# Single agent reward configuration

SUCCESS_REWARD_SINGLE = 10.0
HIGH_PRIORITY_BONUS_SINGLE = 5.0

# Multi-agent reward configuration

# Success rewards
SUCCESS_REWARD = 1.0

# Priority bonuses
HIGH_PRIORITY_BONUS = 0

# Penalties
COLLISION_PENALTY = 1.0
LATENCY_PENALTY_COEFF = 0
QUEUE_PENALTY_COEFF = 0

# Centralized reward configuration
CENTRAL_TX_REWARD = 0.1
CENTRAL_COLLISION_PENALTY = 0.1
CENTRAL_IDLE_PENALTY_BASE = 0.1
CENTRAL_IDLE_PENALTY_FACTOR = 0.01
